### ISSUE TITLE
Nested code blocks don't render due to __OUTPUT__ parsing

### ISSUE THREAD

**Issue by josh-heyer** [rocketinsights/edb_docs#174]
In Markdown, nesting code blocks should be possible (insofar as the "nested" block is just rendered as code. Example:

    ~~~markdown
    ```bash
    cat /etc/lsb-release
    ```
    ~~~

Should render as:

~~~markdown
```bash
cat /etc/lsb-release
```
~~~

However, nothing is rendered for the block at all when this is done.

Thought I had a workaround, but turns out that breaks too - naked `<pre>` blocks also fail:

~~~
<pre>
```bash
cat /etc/lsb-release
```
</pre>
~~~

But, the __OUTPUT__ parsing errors:

> TypeError: children.props is undefined
> 
>     > 117 | const CodeBlock = ({ children, katacodaPanelData, ...otherProps }) => {

Ok, I thought; how about going the whole way and using both `<pre>` and `<code>`?

~~~
<pre><code>
```bash
cat /etc/lsb-release
```
</code></pre>
~~~

Buuut... the __OUTPUT__ parsing vomits on this too:

> TypeError: children.props.className is undefined
>
>      120 |   const language = children.props.className.replace('language-','');

**Comment by epbarger** [comment]
This should be fixed by https://github.com/rocketinsights/edb_docs/pull/175 , let me know if it's still not working for you. If you have issues can you add your example to `docs/playground/1/01_examples/code-blocks.mdx` ?

As a side note, the `__OUTPUT__` parsing does not working within a `markdown` syntax highlighed code block, because the markdown highlighter tokenizes `__` separately from `OUTPUT`. So if you need to add an output section to a markdown highlighted codeblock, we'll need to change the magic string, or figure out a way to override it when necessary. Let me know if you think I should work on this!
